### PR TITLE
Extend default filter to allow any registered extension to be loaded

### PR DESCRIPTION
**Pull request by madscoaducom**
Hi.

I am using the nice SocketStream framework in combination with a coffee-script derivative called [LiveScript](http://gkz.github.com/LiveScript/). I would very much like to work directly with LiveScript files on the server side and as SocketStream uses apitree to load and build the sever side api, it would be great if you could update apitree.js to allow loading of modules with any registered module extension (in require.extensions).

I originally opened a pull request towards SocketStream [#254](https://github.com/socketstream/socketstream/pull/254) to have it use the apitree filter option, but have since realized that the change belongs in apitree, allowing others users of apitree to benefit from this, while at the same time simplifying the impact on SocketStream.

I have put together this pull request which implements the feature. It includes the change to the default filter, updated spec tests and updates to doc to reflect the change. I have run the tests on node.js v0.8.2 and v0.6.19. I tried running the tests on v0.4.12 but I couldn't get the installed mocha to behave. I have done some manual testing on node 0.4 to check that the code should work there.

I hope you will accept this request and publish a new version of apitree.js, Fell free to ask for changes or more tests.

Kind regards
Mads

### CODE REVIEW

**Comment by andreyvit** [comment]
Hey! I've merged your pull request, and also pushed some package.json changes I had to make. However, your new test does not pass on my node 0.6.15:

```
✖ 1 of 48 tests failed:

1) API tree default filter callback should include registered extension files that don't have corresponding .js files:

AssertionError: false == true
    at Context.<anonymous> (/Users/andreyvit/dev/mini/apitree.js/test/apitree_test.coffee:291:23)
    at Test.run (/Users/andreyvit/dev/mini/apitree.js/node_modules/mocha/lib/runnable.js:184:32)
    at Runner.runTest (/Users/andreyvit/dev/mini/apitree.js/node_modules/mocha/lib/runner.js:300:10)
    at /Users/andreyvit/dev/mini/apitree.js/node_modules/mocha/lib/runner.js:346:12
    at next (/Users/andreyvit/dev/mini/apitree.js/node_modules/mocha/lib/runner.js:228:14)
    at /Users/andreyvit/dev/mini/apitree.js/node_modules/mocha/lib/runner.js:237:7
    at next (/Users/andreyvit/dev/mini/apitree.js/node_modules/mocha/lib/runner.js:185:23)
    at Array.0 (/Users/andreyvit/dev/mini/apitree.js/node_modules/mocha/lib/runner.js:205:5)
    at EventEmitter._tickCallback (node.js:192:40)
```

Can you please have a look why? Which Node versions did you test it on? The code looks like it should work.

**Comment by andreyvit** [comment]
Oh, and: I didn't realize SocketStream actually switched to using my package. Thanks for letting me know about that!

**Comment by andreyvit** [comment]
Aw, sorry, my bad. Forgot to recompile .coffee in lib/. Now it works, will release an update.

**Comment by madscoaducom** [comment]
Thank you, for your quick response.

**Comment by andreyvit** [comment]
v1.1.0 has been released on npm. Please test SocketStream with it, and then submit a pull request to SS to update the version number.

**Comment by madscoaducom** [comment]
Will start testing. Thanks.

**Comment by madscoaducom** [comment]
For your reference: https://github.com/socketstream/socketstream/pull/264

**Pull request merged**
